name: verification
# either manually started, or on a schedule
on: [ push, workflow_dispatch, pull_request ]
jobs:
  verification:
    env:
        OPENLANE_ROOT:      /home/runner/openlane
        PDK_ROOT:           /home/runner/pdk
        PDK:                sky130A

    # ubuntu
    runs-on: ubuntu-latest
    steps:
    # need the repo checked out
    - name: checkout repo
      uses: actions/checkout@v3

    # install the tt tools
    - name: checkout tt tools repo
      uses: actions/checkout@v3
      with:
        repository: tinytapeout/tt-support-tools
        ref: tt03p5
        path: tt

    # install the tt mux
    - name: checkout tt mux repo
      uses: actions/checkout@v3
      with:
        repository: tinytapeout/tt-multiplexer
        path: tt-multiplexer
        ref: tt03p5-openlane2

    # install oss fpga tools for cocotb and iverilog
    - name: install oss-cad-suite
      uses: YosysHQ/setup-oss-cad-suite@v2
      with:
          version: '2022-09-03' # pin the version, latest one fails to work with caravel
          github-token: ${{ secrets.GITHUB_TOKEN }}

    # Set Python up
    - name: setup python
      uses: actions/setup-python@v4
      with:
        python-version: '3.10'
    - run: pip install -r tt-multiplexer/py/requirements.txt
    - run: pip install -r tt/requirements.txt

    # fetch the repos - test mode
    - name: fetch all
      run: python ./tt/configure.py --clone-all --fetch-gds --debug --test
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

    # install projects
    - name: configure for test
      run: python ./tt/configure.py --update-caravel --test

    # generate the tt mux verilog that instantiates all the modules - use the test version
    - name: module config
      working-directory: tt-multiplexer
      run: |
        cp ../test_modules.yaml cfg/modules.yaml
        make gensrc

    # run first set of tests
    - name: basic simulations
      run: |
        cd verilog/dv/mux
        make clean test_mux
